# Default values for helmweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

goweb:
    name: goweb
    image:
        repository: grethinam/goweb
        tag: latest
        pullPolicy: Always
        imagePullSecrets: mydockerhubregistrykey
    type: LoadBalancer
    containerPort: 8080

ingress:
  enabled: false