apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.goweb.name }}
  labels:
    app: {{ .Values.goweb.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.goweb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.goweb.name }}
    spec:
      containers:
      - name: {{ .Values.goweb.name }}
        image: {{ .Values.goweb.image.repository }}:{{ .Values.goweb.image.tag }}
        imagePullPolicy: {{ .Values.goweb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.goweb.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.goweb.image.imagePullSecrets }}