apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.goweb.name }}
spec:
  selector:
    app: {{ .Values.goweb.name }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.goweb.containerPort }}
    targetPort: {{ .Values.goweb.containerPort }}
  type: {{ .Values.goweb.type }}
  
  